### PR TITLE
Support unions with up to 26 alternatives

### PR DESCRIPTION
**Pull request by marlonjan**

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Explain.

**Comment by marlonjan** [comment]
This pull request adds support for unions with up to 26 alternatives. Previously, unions were limited to 17 alternatives.

**Comment by ianstormtaylor** [comment]
Why?

**Comment by marlonjan** [comment]
While converting existing TypeScript type definitions to `superstruct` schemas, I got stuck in our codebase when I ran into a union type that had more than 17 alternatives. I think 21 it was in our case. This PR covers up to 26 alternatives, that was as much as I managed to cover while sticking to single letters for type variables.

Do you have any concerns?

**Comment by ianstormtaylor** [comment]
Can you give an example of the union? I'm just thinking that it was `17` before (no idea why tbh), this makes it `26`, someone's going to come along needing `31` next…

**Comment by marlonjan** [comment]
Sure. I can't disclose our actual union type, but here is one I made up with the same structure as the one we have in our project:

```typescript
type Notification =
    | { tag: 'KitchenIsBurning' }
    | { tag: 'RoofIsBurning' }
    | { tag: 'WaterSpill' }
    | { tag: 'DogIsHungry' }
    | { tag: 'CatIsHangry' }
    | { tag: 'NuclearDisaster' }
    | { tag: 'YouLookGreat' }
    | { tag: 'CatsAreBetterThanDogs' }
    | { tag: 'BoringNotification' }
    | { tag: 'GoodNotification' }
    | { tag: 'BestNotification' }
    | { tag: 'UberNotification' }
    | { tag: 'NotificationWithContent'; content: string }
    | { tag: 'AnotherNotificationWithContent'; content: string }
    | { tag: 'YouGetTheIdea'; content: string }
    | { tag: 'YouGetTheIdea2'; content: string }
    | { tag: 'YouGetTheIdea3'; content: string }
    | { tag: 'YouGetTheIdea4'; content: string }
    | { tag: 'YouGetTheIdea5'; content: string }
    | { tag: 'YouGetTheIdea6'; content: string[] }
    | { tag: 'YouGetTheIdea7'; content: string[] }
    | { tag: 'YouGetTheIdea8'; content: string[] }
    | { tag: 'YouGetTheIdea9'; content: string[] }
    | { tag: 'YouGetTheIdea10'; content: string[] };
```

**Comment by Shakeskeyboarde** [comment]
For arbitrary numbers of unions, a progressive/fluent api might be a better approach.

```ts
union(literal('a'))
  .or(literal('b'))
  .or(literal('c'))
  // ...to infinity.
```

**Pull request closed without merging**
