### PR TITLE
Rename CommonJS bundle so as to be compatible with React Native

### LINKED ISSUE #1085: Rename files to `cjs.js` for compatibility with React Native
Importing @solana/web3.js in React Native throws the following error.

```
error: Error: While trying to resolve module `superstruct` from file `/Users/sluscher/mobile-wallet-adapter/js/node_modules/@solana/web3.js/lib/index.browser.cjs.js`, the package `/Users/sluscher/mobile-wallet-adapter/js/node_modules/superstruct/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/sluscher/mobile-wallet-adapter/js/node_modules/superstruct/lib/index.cjs`. Indeed, none of these files exist:

  * /Users/sluscher/mobile-wallet-adapter/js/node_modules/superstruct/lib/index.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

You can see that the React Native packager expects a `.js` extension in addition to `.cjs`

If `superstruct` could rename the CommonJS bundles from `.cjs` to `.cjs.js` that would make it Just Work™ for React Native folks!

More details on the problem here, if you're interested: https://github.com/facebook/metro/issues/535

### PR DESCRIPTION
**Pull request by steveluscher**
Fixes #1085. Read more about the problem statement there.

#### Summary of changes:

* Tests now run against the raw Typescript source. This was necessary because Mocha is awful and renaming the `cjs` bundle caused the entire test system to fall apart. The one I put in place is faster, and unlocks watch mode (`yarn test --watch`)
* Renamed CommonJS bundle to `cjs.js`

### CODE REVIEW

**Comment by steveluscher** [comment]
Hey @ianstormtaylor, do you have a moment to smash this in? I'd like to release and announce the Solana React Native SDK but this is the last thing preventing me from giving people a good ‘Quick Start’ experience without extra configuration.

**Comment by steveluscher** [comment]
Pretty please? I _really_ want to be able to remove this patch as a line in my Getting Started README :)

**Comment by amaranth** [comment]
Why does this also change the test setup and all the tests?

**Comment by steveluscher** [comment]
I made this PR so long ago that the only thing I remember about the changes to the test system is what I wrote in the PR summary itself.

**Comment by ianstormtaylor** [comment]
Hey @steveluscher, very sorry for the delay here. Thank you for putting this together, and makes sense to test directly from source.

**Comment by ianstormtaylor** [comment]
Sorry I should have looked more closely, but I've reverted this change. This is an upstream issue (`.cjs` and `.mjs` files should be recognized by Metro) and it looks like it has been fixed upstream.

**Comment by steveluscher** [comment]
Haha. True. Since I made this change, Metro got its shit together. Thanks anyway!

**Pull request merged**
