### PR TITLE
Type Definitions

### PR DESCRIPTION
**Pull request by edwardsnare**
Added some basic TypeScript definitions. Hoping they're a helpful start for #40

### CODE REVIEW

**Comment by ianstormtaylor** [comment]
Hey @edwardsnare, thanks for this! Would you mind pull requesting these to DefinitelyTyped or whatever the best practice is for the community? Since this codebase isn't typed itself and I don't use TypeScript I'm not going to be able to maintain these myself. Thanks!

**Comment by sunnyvempati** [comment]
@edwardsnare do you have plans to create a PR in the DefinitelyTyped repo?  I could use this.

**Comment by edwardsnare** [comment]
Alright, let me get this PR started @ianstormtaylor  @sunnyvempati

**Comment by siteriaitaliana** [comment]
@edwardsnare any progress with this MR into DefinitelyTyped ?

**Comment by edwardsnare** [comment]
Just made [the pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27392)

**Comment by edwardsnare** [comment]
Hey guys,

The type definitions are out:

[https://npmjs.com/package/@types/superstruct](https://npmjs.com/package/@types/superstruct)

**Pull request closed without merging**
