### PR TITLE
intersection struct should contain all errors of intersected child structs

### PR DESCRIPTION
**Pull request by toxsick**
In the spirit of my previous PR #112 I came across an issue with the intersection struct. Currently it will only return the errors of the first child struct that throws an error. I changed the intersection struct to return all errors now.

This is still not covered by the testsuite though, since the returned errors are not part of it.

Tell me what you think.

cheers

### CODE REVIEW

**Comment by toxsick** [comment]
@ianstormtaylor did u find the time to have a look at this?

**Comment by toxsick** [comment]
New year new try, any updates on this @ianstormtaylor ?

Thanks and happy new year

**Comment by ianstormtaylor** [comment]
Hey @toxsick sorry for the silence here. Can you add a test to ensure this continues to work in the future? Thanks.

**Comment by toxsick** [comment]
Hey @ianstormtaylor, sorry but I missed this one. As I stated initally the problem is that the testsuite does not check the errors that are returned. This has not changed right?

**Comment by ianstormtaylor** [comment]
@toxsick it doesn't currently, but it can be an opt-in if the expected object includes a `failure` property, which should work in this case.

**Pull request closed without merging**
